"use client"

import Link from "next/link"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { FileText, ExternalLink } from "lucide-react"
import { getAvailableDemoWorkflows } from "@/lib/demo-data"
import { WorkflowStorage } from "@/lib/storage"
import { useEffect, useState } from "react"

export default function ReportsIndexPage() {
  const [templates, setTemplates] = useState<any[]>([])

  useEffect(() => {
    const demoWorkflows = getAvailableDemoWorkflows()
    const allTemplates = WorkflowStorage.getTemplates().filter((t) =>
      demoWorkflows.includes(t.id)
    )
    setTemplates(allTemplates)
  }, [])

  return (
    <div className="max-w-7xl mx-auto px-4 py-16">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-4">Security Report Demos</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          See live examples of professional security reports generated by TopFlow&apos;s AI workflows.
          All reports use demo data and are safe to share.
        </p>
      </div>

      {templates.length === 0 ? (
        <div className="text-center py-12">
          <p className="text-muted-foreground">Loading demo reports...</p>
        </div>
      ) : (
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {templates.map((template) => (
            <Card
              key={template.id}
              className="hover:border-primary/50 transition-all hover:shadow-lg hover:shadow-primary/10"
            >
              <CardHeader>
                <div className="flex items-start justify-between mb-2">
                  <Badge variant="outline" className="capitalize">
                    {template.category}
                  </Badge>
                  <FileText className="h-5 w-5 text-muted-foreground" />
                </div>
                <CardTitle className="text-lg">{template.name}</CardTitle>
                <CardDescription className="line-clamp-2">{template.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2 mb-4">
                  {template.compliance?.slice(0, 2).map((framework: string) => (
                    <Badge key={framework} variant="secondary" className="text-xs">
                      {framework}
                    </Badge>
                  ))}
                  {template.compliance && template.compliance.length > 2 && (
                    <Badge variant="secondary" className="text-xs">
                      +{template.compliance.length - 2}
                    </Badge>
                  )}
                </div>
                <Link href={`/reports/${template.id}`}>
                  <Button className="w-full">
                    View Demo Report
                    <ExternalLink className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* CTA Section */}
      <section className="mt-16 p-8 bg-primary/5 border border-border rounded-lg text-center">
        <h2 className="text-2xl font-bold mb-4">Ready to Build Your Own Workflows?</h2>
        <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
          These are just examples. Use TopFlow to create custom security workflows tailored to your
          organization&apos;s needs.
        </p>
        <div className="flex justify-center gap-4">
          <Link href="/builder">
            <Button size="lg">Try Builder</Button>
          </Link>
          <Link href="/">
            <Button size="lg" variant="outline">
              Learn More
            </Button>
          </Link>
        </div>
      </section>
    </div>
  )
}
